In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/aman9801/multiple-linear-regression-on-housing-dataset/main/mlr_housing.csv')
data.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
data['mainroad'] = data['mainroad'].replace({'yes': 1, 'no': 0})
data['guestroom'] = data['guestroom'].replace({'yes': 1, 'no': 0})
data['basement'] = data['basement'].replace({'yes': 1, 'no': 0})
data['hotwaterheating'] = data['hotwaterheating'].replace({'yes': 1, 'no': 0})
data['airconditioning'] = data['airconditioning'].replace({'yes': 1, 'no': 0})
data['prefarea'] = data['prefarea'].replace({'yes': 1, 'no': 0})
furnishingstatus=LabelEncoder()
data['furnishingstatus']=furnishingstatus.fit_transform(data['furnishingstatus'])

In [ ]:
data.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
5,10850000,7500,3,3,1,1,0,1,0,1,2,1,1
6,10150000,8580,4,3,4,1,0,0,0,1,2,1,1
7,10150000,16200,5,3,2,1,0,0,0,0,0,0,2
8,9870000,8100,4,1,2,1,1,1,0,1,2,1,0
9,9800000,5750,3,2,4,1,1,0,0,1,1,1,2

In [ ]:
# Extract independent and dependent variable
x = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus']
x = data[x].values
x

array([[7420,    4,    2, ...,    2,    1,    0],
       [8960,    4,    4, ...,    3,    0,    0],
       [9960,    3,    2, ...,    2,    1,    1],
       ...,
       [3620,    2,    1, ...,    0,    0,    2],
       [2910,    3,    1, ...,    0,    0,    0],
       [3850,    3,    1, ...,    0,    0,    2]])

In [ ]:
y = data.price.values
y

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000,  9240000,  9100000,  9100000,  8960000,
        8890000,  8855000,  8750000,  8680000,  8645000,  8645000,
        8575000,  8540000,  8463000,  8400000,  8400000,  8400000,
        8400000,  8400000,  8295000,  8190000,  8120000,  8080940,
        8043000,  7980000,  7962500,  7910000,  7875000,  7840000,
        7700000,  7700000,  7560000,  7560000,  7525000,  7490000,
        7455000,  7420000,  7420000,  7420000,  7350000,  7350000,
        7350000,  7350000,  7343000,  7245000,  7210000,  7210000,
        7140000,  7070000,  7070000,  7035000,  7000000,  6930000,
        6930000,  6895000,  6860000,  6790000,  6790000,  6755000,
        6720000,  6685000,  6650000,  6650000,  6650000,  6650000,
        6650000,  6650000,  6629000,  6615000,  6615000,  6580000,
        6510000,  6510000,  6510000,  6475000,  6475000,  6440000,
        6440000,  6419000,  6405000,  6300000,  6300000,  6300000,
        6300000,  6300000,  6293000,  6265000,  6230000,  6230000,
        6195000,  6195000,  6195000,  6160000,  6160000,  6125000,
        6107500,  6090000,  6090000,  6090000,  6083000,  6083000,
        6020000,  6020000,  6020000,  5950000,  5950000,  5950000,
        5950000,  5950000,  5950000,  5950000,  5950000,  5943000,
        5880000,  5880000,  5873000,  5873000,  5866000,  5810000,
        5810000,  5810000,  5803000,  5775000,  5740000,  5740000,
        5740000,  5740000,  5740000,  5652500,  5600000,  5600000,
        5600000,  5600000,  5600000,  5600000,  5600000,  5600000,
        5600000,  5565000,  5565000,  5530000,  5530000,  5530000,
        5523000,  5495000,  5495000,  5460000,  5460000,  5460000,
        5460000,  5425000,  5390000,  5383000,  5320000,  5285000,
        5250000,  5250000,  5250000,  5250000,  5250000,  5250000,
        5250000,  5250000,  5250000,  5243000,  5229000,  5215000,
        5215000,  5215000,  5145000,  5145000,  5110000,  5110000,
        5110000,  5110000,  5075000,  5040000,  5040000,  5040000,
        5040000,  5033000,  5005000,  4970000,  4970000,  4956000,
        4935000,  4907000,  4900000,  4900000,  4900000,  4900000,
        4900000,  4900000,  4900000,  4900000,  4900000,  4900000,
        4900000,  4900000,  4893000,  4893000,  4865000,  4830000,
        4830000,  4830000,  4830000,  4795000,  4795000,  4767000,
        4760000,  4760000,  4760000,  4753000,  4690000,  4690000,
        4690000,  4690000,  4690000,  4690000,  4655000,  4620000,
        4620000,  4620000,  4620000,  4620000,  4613000,  4585000,
        4585000,  4550000,  4550000,  4550000,  4550000,  4550000,
        4550000,  4550000,  4543000,  4543000,  4515000,  4515000,
        4515000,  4515000,  4480000,  4480000,  4480000,  4480000,
        4480000,  4473000,  4473000,  4473000,  4445000,  4410000,
        4410000,  4403000,  4403000,  4403000,  4382000,  4375000,
        4340000,  4340000,  4340000,  4340000,  4340000,  4319000,
        4305000,  4305000,  4277000,  4270000,  4270000,  4270000,
        4270000,  4270000,  4270000,  4235000,  4235000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4200000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4200000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4193000,  4193000,
        4165000,  4165000,  4165000,  4130000,  4130000,  4123000,
        4098500,  4095000,  4095000,  4095000,  4060000,  4060000,
        4060000,  4060000,  4060000,  4025000,  4025000,  4025000,
        4007500,  4007500,  3990000,  3990000,  3990000,  3990000,
        3990000,  3920000,  3920000,  3920000,  3920000,  3920000,
        3920000,  3920000,  3885000,  3885000,  3850000,  3850000,
        3850000,  3850000,  3850000,  3850000,  3850000,  3836000,
        3815000,  3780000,  3780000,  3780000,  3780000,  3780000,
        3780000,  3773000,  3773000,  3773000,  3745000,  3710000,
        3710000,  3710000,  3710000,  3710000,  3703000,  3703000,
        3675000,  3675000,  3675000,  3675000,  3640000,  3640000,
        3640000,  3640000,  3640000,  3640000,  3640000,  3640000,
        3640000,  3633000,  3605000,  3605000,  3570000,  3570000,
        3570000,  3570000,  3535000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3500000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3500000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3493000,  3465000,  3465000,  3465000,
        3430000,  3430000,  3430000,  3430000,  3430000,  3430000,
        3423000,  3395000,  3395000,  3395000,  3360000,  3360000,
        3360000,  3360000,  3360000,  3360000,  3360000,  3360000,
        3353000,  3332000,  3325000,  3325000,  3290000,  3290000,
        3290000,  3290000,  3290000,  3290000,  3290000,  3290000,
        3255000,  3255000,  3234000,  3220000,  3220000,  3220000,
        3220000,  3150000,  3150000,  3150000,  3150000,  3150000,
        3150000,  3150000,  3150000,  3150000,  3143000,  3129000,
        3118850,  3115000,  3115000,  3115000,  3087000,  3080000,
        3080000,  3080000,  3080000,  3045000,  3010000,  3010000,
        3010000,  3010000,  3010000,  3010000,  3010000,  3003000,
        2975000,  2961000,  2940000,  2940000,  2940000,  2940000,
        2940000,  2940000,  2940000,  2940000,  2870000,  2870000,
        2870000,  2870000,  2852500,  2835000,  2835000,  2835000,
        2800000,  2800000,  2730000,  2730000,  2695000,  2660000,
        2660000,  2660000,  2660000,  2660000,  2660000,  2660000,
        2653000,  2653000,  2604000,  2590000,  2590000,  2590000,
        2520000,  2520000,  2520000,  2485000,  2485000,  2450000,
        2450000,  2450000,  2450000,  2450000,  2450000,  2408000,
        2380000,  2380000,  2380000,  2345000,  2310000,  2275000,
        2275000,  2275000,  2240000,  2233000,  2135000,  2100000,
        2100000,  2100000,  1960000,  1890000,  1890000,  1855000,
        1820000,  1767150,  1750000,  1750000,  1750000])

In [ ]:
# Split The Dataset Into Training And Testing Subset
from sklearn.model_selection import train_test_split
# test_size=0.2 means 20% of the data will be used for Testing and remaining 80% used to training
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train, y_train)

LinearRegression()

In [ ]:
pred_values = mlr.predict(x_test)
pred_values

array([ 4019080.69890147,  6258021.768564  ,  4392719.13411047,
        7335082.21688194,  2892857.56615675,  7084655.57701774,
        3258634.73504731,  3196499.16068631,  3520106.01134941,
        8359610.28845465,  6646926.36096856,  3788844.63269237,
        3734072.96467981,  4616010.40973202,  3946124.94405792,
        2023177.4684687 ,  3975554.48783028,  3624716.9650089 ,
        3210282.74216168,  4668411.38105794,  5893719.66376515,
        6415683.83807236,  4657036.55831934,  2704096.11205267,
        5356909.86181449,  5740682.56798041,  5337586.47961082,
        5444859.96648234,  5702144.57144375,  5865872.30432732,
        3307327.30668416,  6299491.02684292,  7123479.95544321,
        2960326.86653052,  4424323.19483818,  5125081.85591294,
        4947693.93115736,  3629027.81981122,  2975421.52734786,
        3975089.54021919,  8106313.95534003,  5014658.87529549,
        6469749.69804857,  3566139.31348661,  3868652.86219465,
        6344993.74699856,  4482572.73153154,  2740240.0896807 ,
        4105384.15298296,  6518557.36176521,  3976558.93952635,
        7056307.68945588,  2586714.16696756,  2947687.80114418,
        3553624.39318115,  5151386.47910423,  7171548.10937836,
        4052242.7088535 ,  2884254.74264866,  4379165.55939617,
        6066225.12442545,  6751773.9153444 ,  3382551.41414111,
        7251896.59353497,  2681431.47017135,  5138914.7819742 ,
        6685740.04693819,  2619223.8524795 ,  3824989.41251459,
        4995902.7824292 ,  4352358.99961469,  7264572.3528292 ,
        5150347.40449781,  5947769.21201797,  4086573.09797569,
        4549426.52941342,  2958392.04612462,  7660252.98149768,
        2656282.61262027,  3679497.40060293,  4352358.99961469,
        5981887.99426368,  5132525.06975503,  5458725.16176889,
        3822006.6426444 ,  4128176.81504507,  4698794.75914506,
        5027920.21505869,  3913610.13040526,  4296868.64305712,
        3290316.24497529,  5880621.00664528,  3150060.86792802,
        3668445.62490134,  4539382.03106222, 10575679.21780644,
        2971774.44221851,  7093653.99925704,  4418061.7711239 ,
        4577913.07853262,  6542179.32091921,  3322929.37680987,
        4620712.65928556,  3364236.62346778,  7400967.88555256,
        5138942.23888226,  4058811.42233283,  4972825.57184573,
        6367950.02587764])

In [ ]:
from sklearn.metrics import r2_score
acc = r2_score(y_test, pred_values)
print("Accuracy of model is: ", acc*100)

Accuracy of model is:  65.78047592637594

In [ ]:
# Final Predictions
columns = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
           'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
           'parking', 'prefarea', 'furnishingstatus']
user_input = {column: float(input(f"Enter the value for {column}: ")) for column in columns}
user_data = pd.DataFrame([user_input])

user_pred = mlr.predict(user_data)
print("Predicted price:", user_pred[0])

Enter the value for area: 800
Enter the value for bedrooms: 2
Enter the value for bathrooms: 1
Enter the value for stories: 4
Enter the value for mainroad: 2
Enter the value for guestroom: 2
Enter the value for basement: 0
Enter the value for hotwaterheating: 1
Enter the value for airconditioning: 0
Enter the value for parking: 1
Enter the value for prefarea: 1
Enter the value for furnishingstatus: 0
Predicted price: 7071122.738961604